"""Pydantic schemas for the Digital Brain agent system.

Defines all data contracts for knowledge repos, digital threads,
wave states, swarm tasks, commit plans, and agent messages.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Knowledge Repository
# ---------------------------------------------------------------------------

class KnowledgeRepo(BaseModel):
    """A knowledge domain modeled as a virtual GitHub repository."""

    repo_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    domain: str
    description: str = ""
    embedding: List[float] = Field(default_factory=list)
    artifacts: List[str] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    metadata: Dict[str, Any] = Field(default_factory=dict)


class KnowledgeEntry(BaseModel):
    """A single knowledge artifact stored in a repo."""

    entry_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    repo_id: str
    content: str
    embedding: List[float] = Field(default_factory=list)
    source: str = ""
    tags: List[str] = Field(default_factory=list)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Digital Thread
# ---------------------------------------------------------------------------

class DigitalThreadNode(BaseModel):
    """A node in the digital thread — a stitched cross-domain link."""

    node_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    source_repo: str
    target_repo: str
    amplitude: float = 1.0
    phase: float = 0.0
    coherence: float = 1.0
    content_summary: str = ""
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Wave / Physics State
# ---------------------------------------------------------------------------

class WaveState(BaseModel):
    """Quantum-inspired state representing a query in the vector space."""

    state_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    amplitudes: List[float] = Field(default_factory=list)
    phases: List[float] = Field(default_factory=list)
    dimensions: int = 32
    collapsed: bool = False
    observable: Optional[str] = None
    energy: float = 0.0
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Swarm Task / Pipeline
# ---------------------------------------------------------------------------

class SwarmState(str, Enum):
    """FSM states for the agentic swarm pipeline."""

    IDLE = "idle"
    PLANNING = "planning"
    EXECUTING = "executing"
    COMMITTING = "committing"
    MERGED = "merged"
    FAILED = "failed"


class SwarmTask(BaseModel):
    """A work item dispatched within the agentic swarm."""

    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    instruction: str
    state: SwarmState = SwarmState.IDLE
    assigned_agent: str = ""
    result: str = ""
    parent_task_id: Optional[str] = None
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Commit Plan
# ---------------------------------------------------------------------------

class CommitPlan(BaseModel):
    """A structured plan for a git commit generated by the swarm."""

    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    message: str
    files_changed: List[str] = Field(default_factory=list)
    diff_summary: str = ""
    branch: str = "main"
    parent_sha: str = ""
    tasks: List[str] = Field(default_factory=list)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Agent Protocol (A2A via MCP)
# ---------------------------------------------------------------------------

class AgentCapability(BaseModel):
    """Declares what an agent can do in the MCP network."""

    name: str
    description: str = ""
    input_schema: Dict[str, Any] = Field(default_factory=dict)


class AgentHandshake(BaseModel):
    """A2A handshake payload for agent registration."""

    agent_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    agent_name: str
    capabilities: List[AgentCapability] = Field(default_factory=list)
    endpoint: str = ""
    model_id: str = "gpt-4o-mini"
    version: str = "1.0.0"
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class AgentMessage(BaseModel):
    """A message routed between agents in the MCP network."""

    message_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sender: str
    receiver: str
    action: str
    payload: Dict[str, Any] = Field(default_factory=dict)
    reply_to: Optional[str] = None
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Search Results
# ---------------------------------------------------------------------------

class SearchResult(BaseModel):
    """A ranked search result from the physics search engine."""

    entry_id: str
    repo_id: str
    content: str
    score: float
    resonance: float = 0.0
    interference: str = "constructive"
    source: str = ""
